### ISSUE TITLE
Microsoft Edge bugs with lists

### ISSUE THREAD

**Issue by dvnrsn** [CanopyTax/bandicoot#68] opened 2019-10-02 20:40 UTC
Microsoft Edge seems to be surfacing strange bugs with lists. The styling of the buttons are affected when I click ordered/unordered lists.
![codesandboxlist](https://user-images.githubusercontent.com/9112811/66080070-92706900-e522-11e9-8e99-fbbf78253d44.gif)
https://codesandbox.io/s/fervent-brattain-f1100

**Comment by dvnrsn** [comment] 2019-10-02 20:45
started noticing this here... although it is interesting it's not happening everywhere we are using RTE with buttons. Trying to figure out the difference... ![canopylist](https://user-images.githubusercontent.com/9112811/66080364-335f2400-e523-11e9-804e-a413136c710b.gif)

**Comment by dvnrsn** [comment] 2019-10-02 20:57
![canopylistsmiley](https://user-images.githubusercontent.com/9112811/66081068-91403b80-e524-11e9-888f-746680bf5573.gif)
some vanishing icons styling that I need to work through on our end. However, we're not changing any state that should affect mounted components. Why the DOM is changing is confusing and why clicking a list triggers said change is a mystery far beyond me...

**Comment by dvnrsn** [comment] 2019-10-03 00:46
![bottom](https://user-images.githubusercontent.com/9112811/66091427-f3a93400-e544-11e9-9d9e-731ede905949.gif)
interestingly this problem does not exist if it's on bottom, just having the usual strange experiences in edge of clicking buttons unfocusing the RTE

**Comment by internettrans** [comment] 2019-10-03 03:51
I'm watching this, let me know if you want me to jump in to help diagnose

**Comment by dvnrsn** [comment] 2019-10-03 16:11
I'm at a loss as to why the calls bandicoot is making would affect any styling... it seems absolutely ridiculous to suggest, but my only guess is that bandicoot is somehow interrupting/stunning the render/layout of Edge?

Why would this change depending on if the buttons are first or second children of `<RichTextContainer>`? I'm not sure. What do you think Joel?

**Comment by internettrans** [comment] 2019-10-03 20:49
I have no idea, especially with it being Edge-specific.

I'll keep this in my github notifications and if i get a sec i'll open up my windows laptop and look

**Comment by geoctrl** [comment] 2019-10-03 21:43
it seems to be an issue with the svg tag: `<use />` in edge... it looks like edge is losing the shadow root rendering somehow 🤷‍♀ 

I'll keep on looking into it...

**Comment by geoctrl** [comment] 2019-10-03 21:43
I did not mean to close this... whoops

**Comment by dvnrsn** [comment] 2019-10-03 22:23
Canopy's svgs all of a sudden getting lost when clicking lists is just a part of the broader issue of invoking `execCommand('inserOrderdedList')` in Edge. We've already found a workaround for those svgs (geoctrl is experimenting for a better workaround). We need to figure out why Edge is having unintended styling issues in the first place.

**Comment by dvnrsn** [comment] 2019-10-04 00:05
Found what seems to be a useful solution with geoctrl. Including a block level element right before closing `<RichTextContainer/>` seems to solve all known problems #70. Is there a better way you can think of to proceed Joel?
https://codesandbox.io/s/dreamy-maxwell-7qml9

**Comment by internettrans** [comment] 2019-10-04 18:21
I am unable to reproduce the bug on Edge 18.18362. Here's a gif from https://codesandbox.io/s/fervent-brattain-f1100.

![edge-bandicoot](https://user-images.githubusercontent.com/5524384/66230467-7b0bba00-e6a1-11e9-8f5c-78e18190bb9b.gif)

**Comment by dvnrsn** [comment] 2019-10-04 20:01
![unorderedlist](https://user-images.githubusercontent.com/9112811/66235802-291d6100-e6ae-11e9-9ae9-ba422d0d7a13.gif)
~Microsoft EdgeHTML 17.17134~
Microsoft Edge 42.171

Good catch Joel. My PC is out of date. Canopy supports last 3 major versions of Edge. I believe this means ~[18204, 17723 and 17713](https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/)~ 42, 43, 44 (EdgeHTML is the rendering layout engine I think?)

Should we just have consumers of Bandicoot provide their own block level element if support for earlier edge needed?

**Closed as completed** 2019-11-15 01:57 UTC
